services:
  library:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations users &&
      python manage.py makemigrations library &&
      python manage.py migrate users &&
      python manage.py migrate library &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
        - action: rebuild
          path: requirements.txt
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U library_db -d library_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c "sleep 5 && celery -A config worker --loglevel=info"
    depends_on:
      - library
      - redis

volumes:
  my_db:
