# Generated by Django 6.0.1 on 2026-01-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('PD', 'Paid')], default='PN', max_length=2)),
                ('type', models.CharField(choices=[('PM', 'Payment'), ('FN', 'Fine')], max_length=2)),
                ('session_url', models.URLField(max_length=500)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='library.borrowing')),
            ],
        ),
    ]
